### ISSUE TITLE
No color on cargo messages

### ISSUE THREAD

**Issue by pickfire** [nabijaczleweli/cargo-update#136]
```
    Updating registry 'https://github.com/rust-lang/crates.io-index'
```

does not have color. It would be good to show the cargo version with color on an interactive terminal.

**Comment by nabijaczleweli** [comment]
Following [what that funxion has already been through](https://rawcdn.githack.com/nabijaczleweli/cargo-update/doc/cargo_update/ops/fn.update_index.html), I don't think there's much point in mimicking even more parts of cargo (isatty(), presumably, but then what does that make of Win32, also --color=always,auto,never, &c., &c.), especially for something as trite as colours in an insignificant part of the output. If cargo supported update-registry (which it won't: https://github.com/rust-lang/cargo/pull/5961), I'd just fork+exec that, but otherwise meh.

**Comment by pickfire** [comment]
Is it possible to pull cargo as a library or some sort to just run cargo's code directly? Or maybe just force `--color=always` when the user is in a terminal?

**Comment by nabijaczleweli** [comment]
There's a reason I'm not using libcargo (it's a fucking behemoth, and as stable as Rust (not very)). I'm not going to send rogue escapes to teletypes that don't understand them (which is most).
