### ISSUE TITLE
Preserving manually selected features across updates

### ISSUE THREAD

**Issue by tranzystorek-io** [nabijaczleweli/cargo-update#180]
Does `cargo-update` know about any features that were selected during install, or does it do updates with only the defaults?

Case in point: `cargo-expand` has the `prettyplease` feature that has to be enabled by hand, and I'm wondering if it's lost on each update?

**Comment by nabijaczleweli** [comment]
It doesn't, because, fundamentally, that is not saved anywhere in the Cargo metadata. You can [run](https://github.com/nabijaczleweli/cargo-update/blob/master/man/cargo-install-update-config.md) `cargo install-update-config -f prettyplease cargo-expand` which will enable the feature on subsequent updates (i.e. by installing via `cargo install --features=prettyplease cargo-expand`).

**Comment by tranzystorek-io** [comment]
Thank you for the info!

**Comment by dotdash** [comment]
This information is present in the `.crates2.json` file, any chance that could be used?

```json
  "sqlx-cli 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)": {
    "version_req": "0.6.0",
    "bins": [
      "cargo-sqlx",
      "sqlx"
    ],
    "features": [
      "postgres",
      "rustls"
    ],
    "all_features": false,
    "no_default_features": true,
    "profile": "release",
    "target": "x86_64-unknown-linux-gnu",
    "rustc": "rustc 1.64.0 (a55dd71d5 2022-09-19)\nbinary: rustc\ncommit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\ncommit-date: 2022-09-19\nhost: x86_64-unknown-linux-gnu\nrelease: 1.64.0\nLLVM version: 14.0.6\n"
  },
```
