### ISSUE TITLE
Installed git hash doesn't match latest even when they should.

### ISSUE THREAD

**Issue by svmnotn** [nabijaczleweli/cargo-update#55]
I have installed `i3status-rust` from its git repo, and it hasn't had a commit in 4 days, but when I run `cargo install-update -ag` it tries to update it due to it listing a different hash. This has happened with other packages install through git

**Comment by svmnotn** [comment]
I suppose this should be fixed with: [this cargo issue](https://github.com/rust-lang/cargo/issues/4582)

**Comment by svmnotn** [comment]
If we run cargo uninstall followed by an install from the git repo the issue is solved. This is how I've been temporarily fixing it, thus only using cargo update to tell me the version changed.

**Comment by matthiaskrgr** [comment]
Is there a way to
1) check if the package needs update, if yes
2) do a release build, if release build succeeds
3) cargo uninstall the old version
4) reinstall the new version (without having to rebuild)
?

IMO just uninstalling first and then trying to build the latest version is bad because if build fails, we end up with no running version on the system.

**Comment by mati865** [comment]
The fix has made it through and is available from `rustc 1.28.0-nightly (5bf68db6e 2018-05-28)` onwards.

**Comment by mati865** [comment]
Rust 1.28 is [stable already](https://blog.rust-lang.org/2018/08/02/Rust-1.28.html).

**Comment by nabijaczleweli** [comment]
Thanks for watching out!
